// Every string the web app shows, in one place, so another language can be added later.
export const strings = {
  loading: "Loading…",
  signIn: "Sign in",
  signOut: "Sign out",
  signedInAs: (email: string, admin: boolean) => (admin ? `${email}, admin` : email),
  failed: (message: string) => `Duva couldn't load: ${message}. Reload the page to try again.`,
  signedOut: {
    title: "Sign in to Duva",
    lead: "Your mail and your agents' approvals, on your organization's own domain.",
  },
  sessionEnded: {
    title: "Your session has ended",
    lead: "Sign in again to see your mail and approvals.",
  },
  /** A tab's title: the view, with how many in it want the human, if any do. */
  title: (view: string, count = 0) => (count > 0 ? `${view} (${count}) · Duva` : `${view} · Duva`),
  mailboxesFailed: "Duva couldn't list your mailboxes. Try again in a moment.",

  mailboxes: {
    label: "Mailboxes",
    yours: "Your mailbox",
    agents: "Agents",
    unread: (count: number) => `${count} unread`,
  },

  nav: { label: "Duva", mail: "Mail", approvals: "Approvals", settings: "Settings", waiting: (count: number) => `, ${count} waiting`, write: "Write" },
  connection: {
    upToDate: (time: string) => `Up to date at ${time}`,
    unreachable: "Duva couldn't check for new requests. It tries again by itself.",
    mailUnreachable: "Duva couldn't check for new mail. It tries again by itself.",
  },

  inbox: {
    title: "Inbox",
    agentTitle: (agent: string) => `${agent}'s Inbox`,
    threads: "Threads",
    unread: (count: number, more: boolean) => (more ? `At least ${count} unread` : `${count} unread`),
    unreadMark: "Unread",
    messages: (count: number) => `${count} messages`,
    labelled: (names: string[]) => `labelled ${list(names)}`,
    older: "Show older threads",
    loadingOlder: "Loading older threads…",
    arrived: (count: number) => (count === 1 ? "1 new thread" : `${count} new threads`),
    emptyTitle: "Your Inbox is empty",
    agentEmptyTitle: (agent: string) => `${agent}'s Inbox is empty`,
    emptyLead: (address: string) => `Mail to ${address} appears here. This page checks for new mail by itself, so there's no need to reload it.`,
    noMailboxTitle: "You don't have a mailbox yet",
    noMailboxLead: "Ask an admin to give you one. Your mail appears here once you have it.",
    noMailboxSponsor: "You can still decide what your agents ask to send in Approvals.",
    unknownMailboxTitle: "This mailbox isn't yours to read",
    unknownMailboxLead: "You can read your own mailbox, and those of the agents you sponsor.",
    failed: (status: number) => `Duva couldn't list your threads (error ${status}). Try again in a moment.`,
    unreachable: "Duva couldn't be reached, so your threads aren't listed. Check your connection and try again.",
    retry: "Try again",
  },

  sent: {
    title: "Sent",
    emptyTitle: "Nothing sent yet",
    emptyLead: "Threads you send mail in appear here, newest first. Write a message, or reply to one in your Inbox.",
    agentTitle: (agent: string) => `${agent}'s Sent`,
    agentEmptyTitle: (agent: string) => `${agent} hasn't sent anything yet`,
    agentEmptyLead: (agent: string) => `Threads ${agent} sends mail in appear here, newest first, once you approve its sends.`,
  },

  drafts: {
    title: "Drafts",
    list: "Drafts",
    emptyTitle: "No drafts",
    emptyLead: "Duva saves what you write as you type, so a message you haven't sent waits here until you finish it.",
    noRecipients: "No recipients yet",
    to: (recipients: string) => `To ${recipients}`,
    states: { failed: "Not sent", approved: "Sending", sending: "Sending", unclear: "Unclear" } as Partial<Record<string, string>>,
    failed: (status: number) => `Duva couldn't list your drafts (error ${status}). Try again in a moment.`,
    unreachable: "Duva couldn't be reached, so your drafts aren't listed. Check your connection and try again.",
  },

  compose: {
    newMessage: "New message",
    reply: "Reply",
    forward: "Forward",
    draft: "Draft",
    backToThread: "Thread",
    backToDrafts: "Drafts",
    from: "From",
    to: "To",
    cc: "Cc",
    bcc: "Bcc",
    addCopies: "Add Cc or Bcc",
    bccHint: "Bcc recipients get the message, but nobody sees that they did.",
    toHint: "Separate addresses with commas.",
    subject: "Subject",
    message: "Message",
    send: "Send",
    sendAgain: "Send again",
    delete: "Delete draft",
    deleting: "Deleting…",
    saving: "Saving…",
    saved: (time: string) => `Saved at ${time}`,
    saveFailed: "Duva couldn't save the draft. It tries again as you type.",
    notAddress: (address: string) => `“${address}” isn't an email address. Fix it, and Duva saves the rest meanwhile.`,
    noRecipient: "Add a recipient in To, then send.",
    sendFailed: (status: number) => `Duva couldn't send the draft (error ${status}). Try again in a moment.`,
    unreachable: "Duva couldn't be reached, so nothing was sent. Check your connection and try again.",
    deleteFailed: "Duva couldn't delete the draft. Try again.",
    startFailed: "Duva couldn't start the draft. Try again.",
    loadFailed: (status: number) => `Duva couldn't open this draft (error ${status}). Try again in a moment.`,
    gone: "This draft no longer exists.",
    sending: "Sending…",
    sent: "Sent.",
    openThread: "Open the thread",
    refused: "Not sent. Amazon SES refused it, for the reason below. Change the draft and send it again. If the reason is about the deployment, ask your admin.",
    unclear: "Sending stopped before Amazon SES answered, so Duva can't tell whether it went out. Duva won't send it again. Check with the recipients.",
    readOnly: "A sent draft can't change. Write a new message instead.",
  },

  views: {
    label: "Mail",
    inbox: "Inbox",
    sent: "Sent",
    drafts: "Drafts",
    allMail: "All mail",
    spam: "Spam",
    trash: "Trash",
    yourLabels: "Your labels",
    newLabel: "New label",
    unknownLabel: "Label",
    unread: (count: number) => `, ${count} unread`,
    empty: {
      all: { title: "No mail yet", lead: "Every thread is listed here, archived ones too, except those in Spam and Trash." },
      spam: { title: "No spam", lead: "Mail judged to be spam when it arrived, and threads you mark as spam, are listed here, out of your Inbox. Each is erased for good after 30 days here." },
      trash: { title: "Trash is empty", lead: "Threads you move to Trash are listed here until you restore them. Each is erased for good after 30 days here." },
      label: { title: "No threads have this label", lead: "Pick threads in any view, then add the label to them with Labels." },
    },
  },

  organize: {
    toolbar: "Selected threads",
    threadToolbar: "Thread actions",
    selectAll: "Select every thread shown",
    select: (subject: string) => `Select ${subject}`,
    selected: (count: number) => `${count} selected`,
    archive: "Archive",
    moveToInbox: "Move to Inbox",
    spam: "Mark as spam",
    notSpam: "Not spam",
    trash: "Move to Trash",
    restore: "Restore",
    labels: "Labels",
    labelsFor: (count: number) => (count === 1 ? "Labels for this thread" : `Labels for ${count} threads`),
    noLabels: "You have no labels yet.",
    archived: (count: number) => `Archived ${threads(count)}.`,
    inboxed: (count: number) => `Moved ${threads(count)} to the Inbox.`,
    spammed: (count: number) => `Marked ${threads(count)} as spam.`,
    notSpammed: (count: number) => `Moved ${threads(count)} from Spam to the Inbox.`,
    trashed: (count: number) => `Moved ${threads(count)} to Trash.`,
    restored: (count: number) => `Restored ${threads(count)} from Trash.`,
    labelled: (name: string) => (count: number) => `Added ${name} to ${threads(count)}.`,
    unlabelled: (name: string) => (count: number) => `Removed ${name} from ${threads(count)}.`,
    undo: "Undo",
    undone: "Undone.",
    undoFailed: "Duva couldn't undo that. Change the threads back by hand.",
    failed: "Duva couldn't change the threads. Try again.",
  },

  trash: {
    empty: "Empty Trash",
    confirm: "Erase every thread in Trash for good? This can't be undone.",
    erase: "Erase for good",
    erasing: "Erasing…",
    cancel: "Cancel",
    emptied: "Emptied Trash. Its threads are erased for good.",
    failed: (status: number) => `Duva couldn't empty Trash (error ${status}). Try again in a moment.`,
    unreachable: "Duva couldn't be reached, so Trash wasn't emptied. Check your connection and try again.",
  },

  labelForm: {
    newLabel: "New label",
    create: "Create",
    createAndAdd: "Create and add",
    cancel: "Cancel",
    save: "Save",
    rename: "Rename",
    renameLabel: (name: string) => `Rename ${name}`,
    renamed: (name: string) => `Renamed the label to ${name}.`,
    deleteLabel: "Delete label",
    deleting: "Deleting…",
    confirmDelete: (name: string) => `Delete ${name}? Its threads stay, without the label.`,
    deleted: (name: string) => `Deleted the label ${name}. Its threads are still in your mail.`,
    missing: "Give the label a name.",
    taken: (name: string) => `You have a label named ${name} already, or it's a built-in name. Pick another.`,
    failed: (status: number) => `Duva couldn't save the label (error ${status}). Try again in a moment.`,
    unreachable: "Duva couldn't be reached, so the label wasn't saved. Check your connection and try again.",
  },

  thread: {
    reply: "Reply",
    replyAll: "Reply all",
    starting: "Starting…",
    labels: "Labels",
    markUnread: "Mark unread",
    markingUnread: "Marking unread…",
    markFailed: "Duva couldn't mark the thread unread. Try again.",
    markReadFailed: "Duva couldn't mark the thread read, so it still shows as unread. Open it again to retry.",
    messages: "Messages",
    isNew: "New",
    from: "From",
    to: "To",
    cc: "Cc",
    bcc: "Bcc",
    subject: "Subject",
    date: "Date",
    noSubject: "(no subject)",
    plusTag: (recipient: string, tag: string) => `Sent to ${recipient}, with the plus tag ${tag}`,
    sentByYou: "You sent this",
    sentFromMailbox: "Sent from this mailbox",
    sentBy: (agent: string) => `Sent by ${agent}`,
    approvedAsIs: "You approved it as written.",
    approvedEdited: (fields: string[]) => `You approved your version, changing ${list(fields)}.`,
    approvedBySponsor: "Its sponsor approved it.",
    attachments: "Attachments",
    unnamed: "Attachment without a name",
    download: (name: string) => `Download ${name}`,
    downloading: "Downloading…",
    downloadFailed: "Duva couldn't get the attachment. Try again.",
    forward: "Forward",
    attachment: (type: string, size: string) => `${type}, ${size}`,
    showQuoted: "Show quoted text",
    hideQuoted: "Hide quoted text",
    gone: "This thread is no longer in your mailbox.",
    failed: (status: number) => `Duva couldn't open this thread (error ${status}). Try again in a moment.`,
    unreachable: "Duva couldn't be reached, so the thread isn't shown. Check your connection and try again.",
  },

  settings: {
    title: "Settings",
    organization: "Organization",
    organizationLead: "Admins choose these for everyone in the organization.",
    onlyAdmins: "Only admins change these. Ask one if this should change.",
    erasure: {
      legend: "When a thread with an agent's sends is erased",
      lead: "Each send an agent asked for has an approval record: the draft its approver saw, and any change they made.",
      keep: "Keep them",
      keepHint: "They stay as the record of what an agent sent and who approved it. This is the default.",
      erase: "Erase them with the thread",
      eraseHint: "The change feed still shows each decision and who made it, without the text.",
    },
    save: "Save",
    saving: "Saving…",
    saved: "Saved. This applies to threads erased from now on.",
    failed: (status: number) => `Duva couldn't read the settings (error ${status}). Try again in a moment.`,
    unreachable: "Duva couldn't be reached, so the settings aren't shown. Check your connection and try again.",
    saveFailed: (status: number) => `Duva couldn't save the setting (error ${status}). Try again in a moment.`,
    saveUnreachable: "Duva couldn't be reached, so the setting isn't saved. Check your connection and try again.",
  },

  approvals: {
    title: "Approvals",
    waiting: (count: number) => (count === 1 ? "1 waiting" : `${count} waiting`),
    noneWaiting: "Nothing is waiting for you",
    emptyLead: "When an agent you sponsor asks to send mail, its draft appears here. You send it as is, edit it first, or reject it with a note.",
    emptyPolling: "This page checks for new requests by itself, so there's no need to reload it.",
  },

  galley: {
    asks: (agent: string) => `${agent} asks to send`,
    askedAt: (time: string) => `Asked ${time}`,
    anAgent: "An agent",
    isNew: "New",
    original: "The message it answers",
    noOriginal: "This draft starts a new thread.",
    forward: "A forward. The draft quotes the message it forwards, and carries its attachments.",
    originalGone: "A reply. The message it answers is no longer in the mailbox.",
    draft: (agent: string) => `Draft by ${agent}`,
    yourVersion: "Your version",
    changed: (fields: string[]) => (fields.length === 0 ? "No changes yet. Sending now sends the draft as written." : `You changed ${list(fields)}.`),
    fieldNames: { to: "the recipients", subject: "the subject", text: "the text" },
    from: "From",
    to: "To",
    cc: "Cc",
    bcc: "Bcc",
    subject: "Subject",
    date: "Date",
    whenSent: "When you send it",
    noSubject: "(no subject)",
    attachments: (count: number) => (count === 1 ? "1 attachment, not shown" : `${count} attachments, not shown`),
    showAll: "Show the whole message",
    showLess: "Show less",
    disclosure: (agent: string, sponsor: string) => `Sent by ${agent} for ${sponsor}`,
    disclosureNote: "Duva adds this line, so recipients can tell an agent wrote it.",
  },

  decide: {
    send: "Send",
    edit: "Edit",
    reject: "Reject",
    cancel: "Cancel",
    sendEdited: "Send your version",
    toHint: "Separate addresses with commas.",
    rejectWith: "Reject with note",
    note: (agent: string) => `Note for ${agent}`,
    noteHint: (agent: string) => `Say what ${agent} should change. ${agent} sees this note and can ask again.`,
    noteMissing: (agent: string) => `Write a note, so ${agent} knows what to change.`,
    sending: "Sending…",
    rejecting: "Rejecting…",
    unreachable: "Duva couldn't be reached, so nothing was decided. Try again.",
    gone: "This approval no longer exists. Reload the page to see what is waiting.",
    notYours: "Only the agent's sponsor can decide this approval.",
    failed: (status: number) => `Duva couldn't take the decision (error ${status}), so nothing was decided. Try again in a moment.`,
  },

  outcome: {
    sentAsIs: "You approved it as written",
    sentEdited: "You approved your version",
    rejected: "You rejected it",
    elsewhere: "You already decided this elsewhere",
    withdrawnHead: "Withdrawn",
    noLongerWaiting: "No longer waiting",
    note: (note: string) => `Your note: “${note}”`,
    noteFrom: (note: string) => `The note: “${note}”`,
    checking: "Checking how the send went…",
    approved: "Approved. Duva sends it in a moment.",
    sending: "Sending…",
    sent: "Sent.",
    failed: (agent: string) => `Not sent. Amazon SES refused it, for the reason below. ${agent} can revise the draft and ask again. If the reason is about the recipients or the deployment, ask your admin.`,
    sesSaid: (reason: string) => `Amazon SES said: ${reason}`,
    unclear: "Sending stopped before Amazon SES answered, so Duva can't tell whether it went out. Duva won't send it again. Check with the recipients.",
    withdrawn: (agent: string) => `${agent} changed the draft, so this request was withdrawn. If ${agent} asks again, the new draft appears here.`,
    rejectedElsewhere: (agent: string) => `Rejected. ${agent} can revise the draft and ask again.`,
    askedAgain: (agent: string) => `${agent} has since asked again with a revised draft.`,
    unknown: "Duva couldn't read how it went. It checks again with the next update.",
  },
};

/** A size in bytes as people read it: 11 bytes, 12 KB, 1.4 MB. */
export function size(bytes: number): string {
  if (bytes < 1024) return bytes === 1 ? "1 byte" : `${bytes} bytes`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

/** "1 thread", "2 threads". */
function threads(count: number): string {
  return count === 1 ? "1 thread" : `${count} threads`;
}

/** "a", "a and b", "a, b and c". */
function list(items: string[]): string {
  return items.length < 2 ? items.join("") : `${items.slice(0, -1).join(", ")} and ${items.at(-1)}`;
}
